version: "3"
services:
  app:
    container_name: express-mongo
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb-db:/var/lib/mongodb/data
    ports:
      - "27017:27017"
volumes:
  mongodb-db:
